"""
api.py

Phase 13: dedicated JSON endpoints, off the same routes/services structure
that has served the server-rendered HTML dashboard since Phase 5 (see
src/api/main.py's module docstring). Every endpoint here is a thin
wrapper around a service/analytics function that already existed for the
dashboard — this module adds no new business logic, only JSON shaping,
request validation (src/api/schemas.py), and HTTP status codes.

Grouped per the blueprint's roadmap line for Phase 13:
    /stocks /news /company /sentiment /predict /assistant /portfolio

- /stocks, /company, /news: read-only market data (Phases 1-6).
- /sentiment: Phase 7 sentiment scoring.
- /predict: Phase 8 ML predictions + Phase 9 SHAP explanations.
- /assistant: Phase 10 AI research summaries (GET) and Phase 11's RAG
  annual-report Q&A (POST .../ask) — the first time either is reachable
  over HTTP rather than only through the dashboard page / RAG CLI.
- /portfolio: Phase 12 portfolio CRUD + analytics, as JSON instead of
  HTML forms.

All endpoints live under the `/api` prefix so they're clearly separate
from the dashboard's human-facing routes (`/`, `/stocks/{symbol}`,
`/portfolio`), which continue to return HTML unchanged. Interactive docs
for everything in this file are auto-generated by FastAPI at `/docs`.
"""

from typing import Any

from fastapi import APIRouter, HTTPException, Query

from src.analytics.portfolio_metrics import (
    get_portfolio_holdings,
    get_portfolio_summary,
    get_sector_concentration,
)
from src.api.schemas import (
    AssistantAskRequest,
    AssistantAskResponse,
    AssistantInsight,
    CompanyProfile,
    NewsItem,
    PortfolioHoldingRequest,
    PortfolioResponse,
    PredictionResponse,
    PricePoint,
    SentimentResponse,
    SimpleStatus,
    StockDetail,
    StockSummary,
    WatchlistRequest,
)
from src.api.services.overview_service import get_filtered_companies, get_news
from src.api.services.portfolio_service import (
    DEFAULT_USER,
    PortfolioInputError,
    add_or_update_holding,
    add_watch_only,
    remove_holding,
)
from src.api.services.stock_detail_service import (
    get_company_ai_analysis,
    get_company_ml_explanation,
    get_company_ml_prediction,
    get_company_sentiment,
    get_latest_indicator_summary,
    get_price_history,
)
from src.analytics.kpi_calculator import get_company_kpis
from src.genai.llm_utils import LLMConfigError, LLMRequestError
from src.genai.stock_assistant import DISCLAIMER_TEXT, get_company_ai_insight
from src.rag.rag_pipeline import answer_question
from src.utils.database import get_connection
from src.utils.logger import get_logger

logger = get_logger(__name__)

router = APIRouter(prefix="/api", tags=["JSON API"])


def _require_known_symbol(symbol: str) -> str:
    """
    Confirm a symbol exists in the companies table before doing more
    work, so endpoints that don't otherwise distinguish "unknown symbol"
    from "known symbol, no data yet" (e.g. get_company_sentiment(),
    get_news()) can still return a proper 404 for a typo'd/unloaded
    symbol rather than a misleadingly-empty 200.

    Args:
        symbol: Stock ticker symbol as given by the caller.

    Returns:
        The symbol, uppercased.

    Raises:
        HTTPException: 404 if the symbol has no row in companies.
    """
    normalized = symbol.strip().upper()
    query = "SELECT 1 FROM companies WHERE symbol = %s;"

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (normalized,))
            exists = cur.fetchone() is not None

    if not exists:
        raise HTTPException(status_code=404, detail=f"Unknown symbol: {symbol!r}")

    return normalized


# ---------------------------------------------------------------------
# /api/stocks
# ---------------------------------------------------------------------

@router.get("/stocks", response_model=list[StockSummary])
async def list_stocks(
    sector: str | None = Query(default=None, description="Filter to a single exact sector name."),
    search: str | None = Query(default=None, description="Case-insensitive match against symbol or company name."),
) -> list[dict[str, Any]]:
    """List all tracked companies with their latest price, optionally filtered by sector and/or search term."""
    return get_filtered_companies(sector=sector, search=search)


@router.get("/stocks/{symbol}", response_model=StockDetail)
async def get_stock_detail(symbol: str) -> dict[str, Any]:
    """KPIs (price, market cap, sentiment, ML risk) plus the latest technical indicator values for one company."""
    kpis = get_company_kpis(symbol)
    if kpis is None:
        raise HTTPException(status_code=404, detail=f"Unknown symbol: {symbol!r}")

    price_history = get_price_history(symbol)
    return {**kpis, "indicators": get_latest_indicator_summary(price_history)}


@router.get("/stocks/{symbol}/prices", response_model=list[PricePoint])
async def get_stock_prices(symbol: str) -> list[dict[str, Any]]:
    """Full OHLCV price history for one company, oldest first."""
    _require_known_symbol(symbol)
    return get_price_history(symbol)


# ---------------------------------------------------------------------
# /api/news
# ---------------------------------------------------------------------

@router.get("/news", response_model=list[NewsItem])
async def list_news(
    symbol: str | None = Query(default=None, description="Restrict to one company's news."),
    limit: int = Query(default=20, ge=1, le=100),
) -> list[dict[str, Any]]:
    """Recent news articles, most-recent-first, optionally scoped to one company."""
    if symbol is not None:
        _require_known_symbol(symbol)
    return get_news(symbol=symbol, limit=limit)


# ---------------------------------------------------------------------
# /api/company
# ---------------------------------------------------------------------

@router.get("/company/{symbol}", response_model=CompanyProfile)
async def get_company_profile(symbol: str) -> dict[str, Any]:
    """Company fundamentals only (name, sector, industry, market cap, P/E) — a lighter-weight alternative to /api/stocks/{symbol}."""
    kpis = get_company_kpis(symbol)
    if kpis is None:
        raise HTTPException(status_code=404, detail=f"Unknown symbol: {symbol!r}")

    return {
        "symbol": kpis["symbol"],
        "company_name": kpis["company_name"],
        "sector": kpis["sector"],
        "industry": kpis["industry"],
        "market_cap": kpis["market_cap"],
        "pe_ratio": kpis["pe_ratio"],
    }


# ---------------------------------------------------------------------
# /api/sentiment
# ---------------------------------------------------------------------

@router.get("/sentiment/{symbol}", response_model=SentimentResponse)
async def get_sentiment(symbol: str) -> dict[str, Any]:
    """Aggregate sentiment counts plus recent scored articles for one company (Phase 7)."""
    normalized = _require_known_symbol(symbol)
    return {"symbol": normalized, **get_company_sentiment(normalized)}


# ---------------------------------------------------------------------
# /api/predict
# ---------------------------------------------------------------------

@router.get("/predict/{symbol}", response_model=PredictionResponse)
async def get_prediction(symbol: str) -> dict[str, Any]:
    """
    Latest ML trend/risk prediction plus its SHAP feature-contribution
    explanation for one company (Phases 8-9). `prediction` and
    `explanation` are both null (not a 404) if the ML pipeline hasn't
    produced a prediction for this company yet — that's a valid state,
    distinct from an unknown symbol.
    """
    normalized = _require_known_symbol(symbol)
    prediction = get_company_ml_prediction(normalized)
    explanation = get_company_ml_explanation(normalized) if prediction is not None else None
    return {"symbol": normalized, "prediction": prediction, "explanation": explanation}


# ---------------------------------------------------------------------
# /api/assistant
# ---------------------------------------------------------------------

@router.get("/assistant/{symbol}", response_model=AssistantInsight)
async def get_assistant_insight(
    symbol: str,
    refresh: bool = Query(default=False, description="Bypass today's cached analysis and regenerate it."),
) -> dict[str, Any]:
    """
    AI-generated research summary for one company (Phase 10: outlook,
    summary, key considerations). Cached per (symbol, calendar day)
    unless `refresh=true`.
    """
    normalized = _require_known_symbol(symbol)

    try:
        insight = get_company_ai_insight(normalized, force_refresh=refresh)
    except LLMConfigError as exc:
        raise HTTPException(status_code=503, detail=f"AI assistant is not configured: {exc}") from exc
    except LLMRequestError as exc:
        raise HTTPException(status_code=502, detail=f"AI assistant request failed: {exc}") from exc

    if insight is None:
        # get_company_ai_insight() only returns None for an unknown
        # symbol, which _require_known_symbol() above already rules
        # out — kept as a defensive 404 rather than assuming this can't
        # happen, since a symbol could theoretically be removed between
        # the two calls.
        raise HTTPException(status_code=404, detail=f"Unknown symbol: {symbol!r}")

    return {**insight, "disclaimer": DISCLAIMER_TEXT}


@router.post("/assistant/{symbol}/ask", response_model=AssistantAskResponse)
async def ask_assistant(symbol: str, body: AssistantAskRequest) -> dict[str, Any]:
    """
    Ask a question about a company's ingested annual report(s) (Phase 11
    RAG), grounded only in that company's ingested PDF text — the first
    HTTP-reachable entry point for src.rag.rag_pipeline.answer_question(),
    previously only reachable via its CLI (`python -m src.rag.rag_pipeline ask`).
    """
    normalized = _require_known_symbol(symbol)

    try:
        result = answer_question(normalized, body.question, top_k=body.top_k)
    except LLMConfigError as exc:
        raise HTTPException(status_code=503, detail=f"RAG assistant is not configured: {exc}") from exc
    except LLMRequestError as exc:
        raise HTTPException(status_code=502, detail=f"RAG assistant request failed: {exc}") from exc

    if result is None:
        raise HTTPException(
            status_code=404,
            detail=f"No ingested report found for {normalized!r}. Ingest one first: "
            f"python -m src.rag.rag_pipeline ingest --symbol {normalized} --pdf <path>",
        )

    return {
        "symbol": result.symbol,
        "question": result.question,
        "answer": result.answer,
        "sources": result.sources,
    }


# ---------------------------------------------------------------------
# /api/portfolio
# ---------------------------------------------------------------------

@router.get("/portfolio", response_model=PortfolioResponse)
async def get_portfolio(
    user: str = Query(default=DEFAULT_USER, description="Portfolio owner. No login system exists in this project."),
) -> dict[str, Any]:
    """Holdings, portfolio-wide summary, and sector concentration for one user (Phase 12), as JSON."""
    resolved_user = (user or "").strip() or DEFAULT_USER
    return {
        "user_name": resolved_user,
        "holdings": get_portfolio_holdings(resolved_user),
        "summary": get_portfolio_summary(resolved_user),
        "sector_breakdown": get_sector_concentration(resolved_user),
    }


@router.post("/portfolio/holdings", response_model=SimpleStatus, status_code=201)
async def upsert_holding(body: PortfolioHoldingRequest) -> dict[str, str]:
    """Add a new position or update an existing one's shares/cost basis (matched on user_name + symbol)."""
    try:
        add_or_update_holding(
            user_name=body.user_name,
            symbol=body.symbol,
            shares=str(body.shares),
            avg_cost_basis=str(body.avg_cost_basis),
            purchased_at=body.purchased_at.isoformat() if body.purchased_at else None,
        )
    except PortfolioInputError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    return {"status": "ok", "detail": f"Saved {body.symbol.upper()} for {body.user_name}."}


@router.post("/portfolio/watchlist", response_model=SimpleStatus, status_code=201)
async def add_watch_only_entry(body: WatchlistRequest) -> dict[str, str]:
    """Add a symbol with no position (shares=0) — the lighter-weight watchlist-only entry."""
    try:
        add_watch_only(user_name=body.user_name, symbol=body.symbol)
    except PortfolioInputError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    return {"status": "ok", "detail": f"Watching {body.symbol.upper()} for {body.user_name}."}


@router.delete("/portfolio/holdings/{symbol}", response_model=SimpleStatus)
async def delete_holding(
    symbol: str,
    user: str = Query(default=DEFAULT_USER, description="Portfolio owner."),
) -> dict[str, str]:
    """Remove a symbol from a user's portfolio/watchlist entirely (whether a real position or watch-only)."""
    resolved_user = (user or "").strip() or DEFAULT_USER
    remove_holding(user_name=resolved_user, symbol=symbol)
    return {"status": "ok", "detail": f"Removed {symbol.upper()} for {resolved_user}."}
