"""
vector_store.py

Wraps ChromaDB (a persistent, on-disk vector database — see the blueprint's
tech stack) for storing and retrieving embedded report chunks
(src/rag/document_loader.py, src/rag/embeddings.py).

Design: a single ChromaDB collection ("annual_reports") holds chunks from
every company's report, distinguished by a "symbol" field in each
chunk's metadata. Retrieval always filters by symbol (via ChromaDB's
`where` clause), so this is functionally equivalent to one collection per
company without the bookkeeping overhead of managing many collections as
new symbols are ingested.

Embeddings are supplied explicitly (from src.rag.embeddings), not
generated by ChromaDB itself — this project already has a single,
well-tested path to the Gemini embedding endpoint (with its
RETRIEVAL_DOCUMENT / RETRIEVAL_QUERY task-type distinction), and letting
ChromaDB's own embedding_function integration duplicate that would risk
task-type mismatches between what was indexed and what's queried.

Persistence: ChromaDB's PersistentClient writes to vector_db/ (reserved
for this since Phase 0's folder structure — see .gitignore, which
excludes its contents except .gitkeep, since this is a regeneratable
index, not something this repo ships).
"""

from dataclasses import dataclass

import chromadb

from src.rag.document_loader import ReportChunk
from src.utils.config import PROJECT_ROOT
from src.utils.logger import get_logger

logger = get_logger(__name__)

VECTOR_DB_DIR = PROJECT_ROOT / "vector_db"
COLLECTION_NAME = "annual_reports"

# Cached client, built lazily on first use (see get_collection()).
_client: chromadb.ClientAPI | None = None


@dataclass(frozen=True)
class RetrievedChunk:
    """
    One chunk returned from a similarity search.

    Attributes:
        text: The chunk's text content.
        symbol: Which company's report this chunk came from.
        source_file: The original PDF's filename.
        page: The 1-indexed page number the chunk was extracted from.
        distance: ChromaDB's distance metric for this result (lower is
            more similar). Exposed for callers that want to filter out
            weak matches, not currently used to filter automatically —
            see src.rag.rag_pipeline for how "no good match" is handled.
    """

    text: str
    symbol: str
    source_file: str
    page: int
    distance: float


def _chunk_id(chunk: ReportChunk) -> str:
    """
    Build a deterministic ID for a chunk, so re-ingesting the same report
    file upserts existing entries instead of creating duplicates.

    Args:
        chunk: The chunk to build an ID for.

    Returns:
        A string ID unique to this (symbol, source_file, page, chunk_index)
        combination.
    """
    return f"{chunk.symbol}::{chunk.source_file}::p{chunk.page}::c{chunk.chunk_index}"


def get_collection() -> chromadb.Collection:
    """
    Build (on first call) and return a cached handle to the
    "annual_reports" ChromaDB collection, creating the persistent client
    and the collection itself if either doesn't exist yet.

    Returns:
        The ChromaDB collection used for all report chunks.
    """
    global _client

    if _client is None:
        VECTOR_DB_DIR.mkdir(parents=True, exist_ok=True)
        _client = chromadb.PersistentClient(path=str(VECTOR_DB_DIR))
        logger.info("Initialized ChromaDB persistent client at %s", VECTOR_DB_DIR)

    return _client.get_or_create_collection(name=COLLECTION_NAME)


def reset_client() -> None:
    """
    Drop the cached ChromaDB client, forcing the next get_collection()
    call to rebuild it. Used in tests.
    """
    global _client
    _client = None


def add_chunks(chunks: list[ReportChunk], chunk_embeddings: list[list[float]]) -> int:
    """
    Upsert a batch of report chunks and their embeddings into the vector
    store.

    Args:
        chunks: Chunks to store (typically from
            src.rag.document_loader.load_report_chunks()).
        chunk_embeddings: One embedding vector per chunk, in the same
            order (typically from src.rag.embeddings.embed_documents()).

    Returns:
        The number of chunks upserted. 0 if `chunks` is empty (no
        ChromaDB call is made in that case).

    Raises:
        ValueError: If `chunks` and `chunk_embeddings` have different lengths.
    """
    if len(chunks) != len(chunk_embeddings):
        raise ValueError(
            f"chunks ({len(chunks)}) and chunk_embeddings ({len(chunk_embeddings)}) must be the same length."
        )

    if not chunks:
        logger.warning("add_chunks: nothing to add.")
        return 0

    collection = get_collection()
    collection.upsert(
        ids=[_chunk_id(chunk) for chunk in chunks],
        embeddings=chunk_embeddings,
        documents=[chunk.text for chunk in chunks],
        metadatas=[
            {"symbol": chunk.symbol, "source_file": chunk.source_file, "page": chunk.page}
            for chunk in chunks
        ],
    )

    logger.info("Upserted %d chunk(s) into the vector store.", len(chunks))
    return len(chunks)


def query(query_embedding: list[float], symbol: str, top_k: int = 5) -> list[RetrievedChunk]:
    """
    Find the most similar chunks to a query embedding, restricted to one
    company's report(s).

    Args:
        query_embedding: The embedded query (typically from
            src.rag.embeddings.embed_query()).
        symbol: Restrict results to this company's chunks.
        top_k: Maximum number of results to return.

    Returns:
        A list of RetrievedChunk, ordered by similarity (most similar
        first). Empty list if this symbol has no ingested chunks at all.
    """
    collection = get_collection()

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        where={"symbol": symbol.upper()},
    )

    documents = results["documents"][0] if results["documents"] else []
    metadatas = results["metadatas"][0] if results["metadatas"] else []
    distances = results["distances"][0] if results["distances"] else []

    return [
        RetrievedChunk(
            text=document,
            symbol=metadata["symbol"],
            source_file=metadata["source_file"],
            page=metadata["page"],
            distance=distance,
        )
        for document, metadata, distance in zip(documents, metadatas, distances)
    ]


def delete_symbol(symbol: str) -> None:
    """
    Delete every ingested chunk for a company, e.g. before re-ingesting a
    corrected or updated report.

    Args:
        symbol: The company whose chunks should be removed.
    """
    collection = get_collection()
    collection.delete(where={"symbol": symbol.upper()})
    logger.info("Deleted all chunks for %s from the vector store.", symbol.upper())


def count_chunks(symbol: str | None = None) -> int:
    """
    Count ingested chunks, for status checks and tests.

    Args:
        symbol: If provided, count only this company's chunks. If None,
            count every chunk in the collection.

    Returns:
        The chunk count.
    """
    collection = get_collection()

    if symbol is None:
        return collection.count()

    # Collection.count() has no `where` filter, so a symbol-scoped count
    # goes through get() instead, retrieving only IDs (no embeddings/
    # documents) to keep this cheap even for a large collection.
    result = collection.get(where={"symbol": symbol.upper()}, include=[])
    return len(result["ids"])
